spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_management_system?createDatabaseIfNotExist=true
    username: "root"
    password: "root1234"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
